config/routes.rb
Cama::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :admins, :path => 'camaadministrator', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  root "statics#index"

  get 'about' => 'statics#about', :as => :about
  
  resources :pages, :controller => :statics do 
    collection do
      get ':page', :action => :show, :as => :page
    end
  end
  
  resources :categories, :controller => :product_cates, :only => [ :index, :show] do 
    resources :products, :only => [:show]
  end
  # resources :product_cates, :only => [:index, :show] do
  #   resources :products, :only => [:show]
  # end

  resources :cart, :only => [:index, :create] do
    collection do
      get "check" => "cart#check" , :as => "check"
      get "final_check/" => "cart#final_check", :as => "final_check"
      get "finish"
      get "confirm" => "cart#confirm", :as => "confirm"
      #
      post "set_ship_to/:shipping_to" => "cart#set_ship_to" , :as => "set_ship_to"
      get "fail"
      #金流串接
      get "post_order/:id" => "cart#post_order", :as => "post_order"
      get "receive_result" => "cart#receive_result"

      match "add" => "cart#add" , :via => :post
    end

    member do
      match "plus/:index" => "cart#plus" , :via => :post , :as => "plus"
      match "minus/:index" => "cart#minus" , :via => :post , :as => "minus"
      match "delete_by_attribute/:index" => "cart#delete_by_attribute", :via => :post , :as => "delete_by_attribute"
      match "delete" => "cart#delete" , :via => :delete

    end
  end

  namespace :useradmin do
    
    resources :users, :only => [:index ,:update]
    resources :addressbooks , :only => [:index, :create, :destroy ,:update]
    
    
    resources :orders, :only => [:index, :show] do
      member do
        resources :orderasks, :only => [:new, :create]
        patch :atm_transfered #the only action that user allow to triggered
      end
    end
  
    root "orders#index"

  end

  resources :announcements , :only => [:index, :show]

  resources :talks , :only => [:index, :show] do 
    collection do 
      get 'about/:tag', to: 'talks#index', as: :about
    end
  end

  resources :stores do 
    collection do 
      get 'search', action: 'search'
    end
  end

  get 'fetch_from_country' => 'stores#fetch_from_country'
  get 'fetch_from_city' => 'stores#fetch_from_city'

  namespace :admin do

    authenticated :admin do
      root "orders#index"#, :as => :authenticated_root
    end

      mount RailsAdmin::Engine => '/advanced', as: 'rails_admin'
      
      resources :admins
      
      resources :product_cates, :except => [:new, :edit] do
        resources :products, :except => [:index, :new] do
          member do
            post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'

            get   '/basic_info'       => 'products#basic_info', as: 'basic_info'
            patch  '/basic_info'       => 'products#update_basic_info'

            get   '/free_paragraph'       => 'products#free_paragraph'
            post  '/free_paragraph'       => 'products#update'

            post 'create_product_attachment' , :action => 'create_product_attachment'
            post 'create_taste_attachment' , :action => 'create_taste_attachment'
          
            match :productphoto_upload, :via => :get
            match :taste_attributes, :via => :get

            match :change_status, :via => :post

            resources :product_stocks, :only => [:index, :create, :update, :destroy]
          end

          
        end

      end

      # resources :banners
      # #admin/index_sliders, admin/selected_products
      resources :index_sliders, controller: 'banners', type: 'IndexSlider' do
        # member do 
        #   # do or not?
        #   patch 'multiple_reorder' , :action => 'multiple_reorder'
        # end
      end

      resources :selected_products, controller: 'banners', type: 'SelectedProduct' do 
        # member do 
        #   # do or not?
        #   patch 'multiple_reorder' , :action => 'multiple_reorder'
        # end
      end

      resources :jobs 

      resources :stores do

        # edit
        member do 
          get 'fetch_from_country' , action: 'fetch_from_country'
          get 'fetch_from_city' , action: 'fetch_from_city'

          post 'create_store_attachment' , :action => 'create_store_attachment'
          match :storephoto_upload, :via => :get
        end

        # new
        collection do 
          get 'fetch_from_country' , action: 'fetch_from_country'
          get 'fetch_from_city' , action: 'fetch_from_city'
        end
      end

      resources :services do 
        member do 
          post 'create_service_attachment' , :action => 'create_service_attachment'
          match :servicephoto_upload, :via => :get        
        end      
      end

      resources :talks do 
        member do
          post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
          post 'create_talk_attachment' , :action => 'create_talk_attachment'
          match :talkphoto_upload, :via => :get        

          get   '/edit_tags'       => 'talks#edit_tags'
          patch  '/edit_tags'       => 'talks#update_tags'

        end
      end

      resources :announcements do 
        member do
          post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
          post 'create_announcement_attachment' , :action => 'create_announcement_attachment'
          match :announcementphoto_upload, :via => :get

          get '/custom_edit' => 'announcements#custom_edit'
          patch '/custom_edit' => 'announcements#update'

        end
      end

      resources :customizedpages do
        member do
          post 'create_customizedpage_attachment' , :action => 'create_customizedpage_attachment'
          match :customizedpagephoto_upload, :via => :get
        end
      end

      resources :galleries do 
        member do
          patch 'multiple_reorder' , :action => 'multiple_reorder'
        end 
      end


      resources :orders, :only => [:index, :show] do
        member do 
          #AASM
          post :checkout_succeeded_ATM # should remove
          post :cancel_before_paid_ATM
          post :atm_transfered
          post :money_placed_ATM
          post :atm_comfirmed
          
          post :checkout_succeeded_Vaccount # should remove
          post :cancel_before_paid_Vaccount
          post :comfirmed_Vaccount
          #post :human_involving_after_order_placed
          
          post :checkout_succeeded_COD # should remove
          post :shipping_COD
          post :post_collect_checked
          post :human_involving_after_order_placed_COD
          post :human_involving_post_collect_COD

          post :checkout_succeeded_general # should remove
          post :shipping_first
          post :human_involving_after_order_placed_general

          
          #SHARED
          post :checkout_failed # should remove
          post :shipping

          patch :shipping
          patch :shipping_first
          patch :shipping_COD
          patch :human_involving_after_order_placed_COD
          patch :human_involving_post_collect_COD
          patch :human_involving_after_order_placed_general
          patch :human_involving_after_money_placed
          patch :human_involving_after_money_checked
          patch :human_involving_after_shipped
          patch :human_involved_edit
          

          post :human_involved_edit
          post :human_involving_after_money_placed
          post :human_involving_after_money_checked
          post :human_involving_after_shipped
          post :close_deal
          post :to_abnormal

          get '/info_hub/:event' => 'orders#info_hub'
          post '/info_hub/:event' => 'orders#update_from_info_hub'

          get 'detail' => 'orders#detail'

        end

        collection do
          #金流：查詢交易狀態
          get "query_order_status/:id" => "orders#query_order_status", :as => "query_order"
          get "receive_order_status" => "orders#receive_order_status"

          get '/todolist' , action: 'index'
          get '/shipped' , action: 'shipped'
          get '/pending' , action: 'pending'
          get '/human_involved' , action: 'human_involved'
          #get '/history' , action: 'history'
          match 'history' => 'orders#history', via: [:get, :post], as: :history
          
        end

      end

      resources :orderasks, :only => [:index, :update] do
        collection do 
          get 'history', action: 'history'
        end
      end
      resources :users , :only => [:index, :show] do 
        collection do 
          get 'export', action: 'export'
          #get 'search', action: 'search'
        end
      end
      resources :deliveries

      delete 'peditor/deletePhoto/:id'        => 'peditor#destroyPhoto'
        
    

    #get '/camaadministrator/login' => 'devise/sessions#new'
    #unauthenticated :admin do
      #root to: redirect('/camaadministrator/login'), as: 'unauthenticated_root' # => "devise/sessions#new"
    #end
    
  end

  get '(*url)'   => 'errors#index'

end

app/controllers/useradmin/orders_controller.rb
#encoding: utf-8
class Useradmin::OrdersController < UseradminController
  before_action :order_params, only: [:atm_transfered]
  
  def index
    @orders = current_user.orders.where("aasm_state != 'hold'").where("created_at >= ? ", 1.year.ago).order(created_at: :desc)
  end
  
  def show
    @order = current_user.orders.includes(:orderitems).includes(:orderlogs).find_by_id(params[:id])

    if(@order)
    	#@orderask = @order.orderasks.new
    	#@orderasks = Orderask.where(:order_id => @order.id)
    else
    	redirect_to useradmin_orders_path #, alert: "找不到訂單"
    end
  end

  def atm_transfered
    @order = current_user.orders.find_by_id(params[:id])
    
    if @order
      if @order.update(order_params)
        @order.atm_transfered!
        redirect_to :back, notice: "匯款帳號已更新"  
      else
        flash[:notice] = @order.errors.first[1]
        redirect_to :back
      end
    else
      redirect_to useradmin_orders_path #, alert: "找不到訂單"
    end
    
    
  end

  private

  def order_params
    params.require(:order).permit(:accountinfo)
  end

end

app/helpers/orders_helper.rb
#encoding: utf-8
module OrdersHelper
  def sum_order_items(order_items)
    return order_items.inject(0) { | sum, i | sum += i.item_price * i.amount }
  end

  # not in use
  def get_shipping_fee_by_type(order)
    #use in checkout process, should return fee by delivert type
    if order.delivery_type.nil?
      return 120
    else
      return Delivery.find(order.delivery_type).normal_fee
    end

  end

  def get_shipping_fee_from_order(order)
    return order.shipping_fee
  end
  
    # event :checkout_failed do
    # event :checkout_succeeded_ATM do 
    # event :cancel_before_paid_ATM do
    # event :atm_transfered do # ATM only
    # event :atm_comfirmed do
    # event :checkout_succeeded_Vaccount do 
    # event :cancel_before_paid_Vaccount do
    # event :comfirmed_Vaccount do # VAccount only
    # event :checkout_succeeded_general do
    # event :shipping_first do # credit card, 3rd , COD
    # event :human_involving_after_order_placed_general do # credit card, 3rd
    # event :shipping do
    # event :human_involving_after_money_placed do # ATM
    # event :human_involving_after_money_checked do # ATM or VAccount
    # event :human_involving_after_shipped do # credit card, 3rd
    # event :human_involved_edit do
    # event :close_deal do
    # event :to_abnormal do
    # event :checkout_succeeded_COD do
    # event :shipping_COD do 
    # event :post_collect_checked do
    # event :human_involving_after_order_placed_COD do 
  
  def get_event_display_name(event_name)
    case event_name
    when "checkout_failed"
      "使交易失敗"
    when "checkout_succeeded_ATM"
      "使交易成功(ATM)"
    when "cancel_before_paid_ATM"
      "取消"
    when "atm_transfered"
      "已填後五碼"
    when "atm_comfirmed"
      "對賬"
    when "checkout_succeeded_Vaccount"
      "使交易成功(虛擬帳號)"
    when "cancel_before_paid_Vaccount"
      "取消"
    when "comfirmed_Vaccount"
      "對賬"
    when "checkout_succeeded_general"
      "使交易成功(信用卡)"
    when "shipping_first"
      "出貨"
    when "checkout_succeeded_COD"
      "使交易成功(COD)"
    when "shipping_COD"
      "出貨"
    when "post_collect_checked" #貨到付款對賬
      "對賬"
    when "human_involving_after_order_placed_general"
      "人為處理"
    when "human_involving_after_order_placed_COD" #COD
      "人為處理"
    when "human_involving_post_collect_COD" #COD
      "人為處理"
    when "shipping"
      "出貨"
    when "human_involving_after_money_placed"
      "人為處理"
    when "human_involving_after_money_checked"
      "人為處理"
    when "human_involving_after_shipped"
      "人為處理"
    when "human_involved_edit"
      "編輯"
    when "close_deal"
      "完成交易"
    when "to_abnormal"
      "完成"
    else
      "ERR"
    end
  end

  def is_order_paid(order)
    return "<img src='/images/admin/check.png'>".html_safe if order.paid == "yes"
  end

  def is_order_delivered(order)
    return "<img src='/images/admin/check.png'>".html_safe if order.shipped == "yes"
  end

  def ship_to_where(order)
    case order.ship_to
      when 'taiwan'
        "本島"
      when 'island'
        "離島"
    end
  end

  def fetch_tracking_url(order)
    delivery_type = Delivery.find_by_id(order.delivery_type)
    
    if delivery_type
      link_to "進度查詢", delivery_type.tracking_url, target: "_blank"
    else
      "無法產生追蹤聯結"
    end
  end

end

app/views/admin/orders/_atm_confirm.html.erb
<div id="wrapper">
  <div id="up">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td width="24%">後五碼：</td>
            <td width="76%"><%= @order.accountinfo %></td>
        </tr>
        <tr>
            <td width="24%">訂單金額：</td>
            <% @sum = sum_order_items(@order.orderitems) %>
            <% @shipping_fee = get_shipping_fee_from_order(@order)  %>
            <td width="76%">$<%= number_with_delimiter(@sum + @shipping_fee) %></td>
        </tr>
    </table>
  </div>
  <div id="down">
      <%= link_to "取消" , "javascript: void(0);" , class: "cancel" , id: "cancel" %>
      <%= link_to "確認", "/admin/orders/#{@order.id}/#{params[:event]}" , :method => :post , class: "action_confirmed" , id: "send" %>      
  </div>
 </div> 

app/views/admin/orders/_edit_tabs.html.erb
<%= link_to "需處理", admin_orders_path()%>|
<%= link_to "已出貨", shipped_admin_orders_path()%>|
<%= link_to "待付款", pending_admin_orders_path()%>|
<%= link_to "人為處理", human_involved_admin_orders_path()%>|
<%= link_to "歷史訂單", history_admin_orders_path()%>

app/views/admin/orders/history.html.erb
<script src="/js_plugins/colorbox/jquery.colorbox-min.js"></script>
<link rel="stylesheet" type="text/css" href="/js_plugins/colorbox/colorbox.css" />    
<style>
div ,td, p .noTransition {
    -moz-transition: none;
    -webkit-transition: none;
    -o-transition: color 0 ease-in;
    transition: none;
}
</style>
<script>
  $(document).ready(function(){
    
    $(".iframe").colorbox({
      iframe:true, width:"483", height:"320",
      onClosed:function(){ parent.location.reload(); }
    });

  });
</script>

<header>
  <h2 class="left">訂單管理</h2>
  <nav class="left">
    <%= link_to "待付款", pending_admin_orders_path()  %>
    <%= link_to "需處理", admin_orders_path()%>
    <%= link_to "已出貨", shipped_admin_orders_path()%>    
    <%= link_to "人為處理", human_involved_admin_orders_path()%>
    <%= link_to "歷史訂單", history_admin_orders_path(), class: 'active' %>
  </nav>
</header>
<article>
      <div class='search'>
       <%# %>
       <%= search_form_for @q, url: history_admin_orders_path, method: :post  do |f| %>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="15%" style="padding:0 5px">
              訂單編號：
            </td>
            <td width="35%">
              <%= f.search_field :ordernum_cont, class: 'text' %>
            </td>
            <td width="15%" style="padding:0 5px">
              Email：
            </td>
            <td width="35%" align="center">
              <%= f.search_field :user_email_start, class: 'text' %>
            </td>
          </tr>
          <tr>
            <td width="15%" style="padding:0 5px">
              付款方式：
            </td>
            <td width="35%">
              <%= f.select :payment_type_eq, options_for_select([['-- 請選擇 --',nil],['ATM','atm_transfer'], ['信用卡', 'credit_card'], ['貨到付款','COD'], ['虛擬帳號','Vaccount']], nil), class: 'form-control' %>
            </td>
            <td width="15%" style="padding:0 5px">
              狀態：
            </td>
            <td width="35%" align="center">
              <%= f.select :payment_status_eq, options_for_select([['-- 請選擇 --',nil],['交易完成','finished'],['交易結束','abnormal_end'], ['取消訂單', 'cancel'], ['交易失敗','failed']], nil ) , class: 'form-control' %>
            </td>
          </tr>
          <tr>
            <td width="15%" style="padding:0 5px">
              收款狀態：
            </td>
            <td width="35%">
              <%= f.select :paid_eq, options_for_select([['-- 請選擇 --',nil],['已付款','yes'],['未付款','no']], nil ) , class: 'form-control' %>
            </td>
            <td width="15%" style="padding:0 5px">
              出貨狀態：
            </td>
            <td width="35%" align="center">
              <%= f.select :shipped_eq, options_for_select([['-- 請選擇 --',nil],['已出貨','yes'],['未出貨','no']], nil ) , class: 'form-control' %>
            </td>
          </tr>
          <tr>
            <td width="15%" style="padding:0 5px">
              期間：
            </td>
            <td width="35%">
              <%= f.select :created_at_gteq, options_for_select([['-- 請選擇 --',nil],['1週',1.week.ago], ['1個月', 1.month.ago], ['1年',1.year.ago]], nil) %>
            </td>
            <td width="15%" style="padding:0 5px">
              
            </td>
            <td width="35%" align="center">
              <%= f.submit('搜尋') %>
            </td>
          </tr>
        </table>
       <% end %>
       <%# %>
      </div>
  <div class="list">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th width="5%" align="center" class="icon"></th>
        <th width="12%" align="center"><%= sort_link @q , :payment_type, "付款方式" %></th>
        <th width="21%" align="left"><%= sort_link @q, :created_at, "訂單成立時間" %></th>
        <th width="16%" align="left"><%= sort_link @q, :ordernum, "編號" %></th>
        <th width="5%" align="center"><a href="javascript:void(0);">收款</a></th>
        <th width="5%" align="center"><a href="javascript:void(0);">出貨</a></th>
        <th width="30%" align="right"><a href="javascript:void(0);">狀態</a></th>
      </tr>

      <% @orders.each do |order| %>
        <tr id="order_<%= order.id %>">
          <td class="icon"></td>
          <td align="center"><%= order.get_payment_type %></td>
          <td><span class="time"><%= order.created_at.strftime("%Y-%m-%d %H:%M") %></span></td>
          <td><%= link_to order.ordernum, admin_order_path(order), :class => "show_order close", :remote => true, :data => { order_id: order.id } %></td>
          <td align="center"><%= is_order_paid(order) %></td>
          <td align="center"><%= is_order_delivered(order) %></td>
          <td align="right"><%= order.get_payment_status %></td>
        </tr>
      <% end %>

    </table>
  </div>
  <div class= "page">
    <%= paginate @orders ,:window => 2 %>
  </div>
</article>

<script type="text/javascript">
$(".show_order").click(function(){
  var $show_order = $("#show_order_" + $(this).data("order-id"))
  if( $show_order.length > 0 ){
    $show_order.stop().toggle();
    return false
  }
  else{
    return true;
  }
});
$(function() {
  $( "#search-accordion" ).accordion({
    collapsible: true,
    active: false
  });
});
</script>

app/views/admin/orders/human_involved.html.erb
<script src="/js_plugins/colorbox/jquery.colorbox-min.js"></script>
<link rel="stylesheet" type="text/css" href="/js_plugins/colorbox/colorbox.css" />    
<style>
div ,td, p .noTransition {
    -moz-transition: none;
    -webkit-transition: none;
    -o-transition: color 0 ease-in;
    transition: none;
}
</style>
<script>
  $(document).ready(function(){
    
    $(".iframe").colorbox({
      iframe:true, width:"483", height:"320",
      onClosed:function(){ parent.location.reload(); }
    });

  });
</script>

<header>
  <h2 class="left">訂單管理</h2>
  <nav class="left">
    <%= link_to "待付款", pending_admin_orders_path()  %>
    <%= link_to "需處理", admin_orders_path()%>
    <%= link_to "已出貨", shipped_admin_orders_path()%>    
    <%= link_to "人為處理", human_involved_admin_orders_path(), class: 'active' %>
    <%= link_to "歷史訂單", history_admin_orders_path()%>
  </nav>
</header>
<article>
  <div class="list">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th width="5%" align="center" class="icon"></th>
        <th width="12%" align="center"><%= sortable "payment_type", "付款方式" %></th>
        <th width="21%" align="left"><%= sortable "created_at", "訂單成立時間" %></th>
        <th width="16%" align="left"><%= sortable "ordernum", "編號" %></th>
        <th width="5%" align="center"><a href="javascript:void(0);">收款</a></th>
        <th width="5%" align="center"><a href="javascript:void(0);">出貨</a></th>
        <th width="30%"></th>
      </tr>

      <% @orders.each do |order| %>
        <tr id="order_<%= order.id %>">
          <td class="icon"></td>
          <td align="center"><%= order.get_payment_type %></td>
          <td><span class="time"><%= order.created_at.strftime("%Y-%m-%d %H:%M") %></span></td>
          <td><%= link_to order.ordernum, admin_order_path(order), :class => "show_order close", :remote => true, :data => { order_id: order.id } %></td>
          <td align="center"><%= is_order_paid(order) %></td>
          <td align="center"><%= is_order_delivered(order) %></td>
          <td>
            <div class="tool">
              <% order.aasm.events.each do |event| %>
                <%= link_to get_event_display_name(event.to_s), "/admin/orders/#{order.id}/info_hub/#{event}" , class: "iframe uvs" %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>

    </table>
  </div>
</article>

<script type="text/javascript">
$(".show_order").click(function(){
  var $show_order = $("#show_order_" + $(this).data("order-id"))
  if( $show_order.length > 0 ){
    $show_order.stop().toggle();
    return false
  }
  else{
    return true;
  }
});
</script>

app/views/admin/orders/pending.html.erb
<script src="/js_plugins/colorbox/jquery.colorbox-min.js"></script>
<link rel="stylesheet" type="text/css" href="/js_plugins/colorbox/colorbox.css" />    
<style>
div ,td, p .noTransition {
    -moz-transition: none;
    -webkit-transition: none;
    -o-transition: color 0 ease-in;
    transition: none;
}
</style>
<script>
  $(document).ready(function(){
    
    $(".iframe").colorbox({
      iframe:true, width:"483", height:"320",
      escKey: false, 
      closeButton: false,
      overlayClose: false,
      onClosed:function(){ parent.location.reload(); }
    });

  });
</script>
<header>
  <h2 class="left">訂單管理</h2>
  <nav class="left">
    <%= link_to "待付款", pending_admin_orders_path(), class: 'active' %>
    <%= link_to "需處理", admin_orders_path() %>
    <%= link_to "已出貨", shipped_admin_orders_path()%>    
    <%= link_to "人為處理", human_involved_admin_orders_path()%>
    <%= link_to "歷史訂單", history_admin_orders_path()%>
  </nav>
</header>
<article>
  <div class="list">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th width="5%" align="center" class="icon"></th>
        <th width="12%" align="center"><%= sortable "payment_type", "付款方式" %></th>
        <th width="21%" align="left"><%= sortable "created_at", "訂單成立時間" %></th>
        <th width="16%" align="left"><%= sortable "ordernum", "編號" %></th>
        <th width="5%" align="center"><a href="javascript:void(0);">收款</a></th>
        <th width="5%" align="center"><a href="javascript:void(0);">出貨</a></th>
        <th width="30%"></th>
      </tr>

      <% @orders.each do |order| %>
        <tr id="order_<%= order.id %>">
          <td class="icon">
            <% if order.payment_type == 'Vaccount' || order.payment_type == 'atm_transfer' %>
              <% unless 4.days.ago < order.created_at %>
                <img src="/images/admin/warn.gif">
              <% end %>
            <% end %>
          </td>
          <td align="center"><%= order.get_payment_type %></td>
          <td><span class="time"><%= order.created_at.strftime("%Y-%m-%d %H:%M") %></span></td>
          <td><%= link_to order.ordernum, admin_order_path(order), :class => "show_order close", :remote => true, :data => { order_id: order.id } %></td>
          <td align="center"><%= is_order_paid(order) %></td>
          <td align="center"><%= is_order_delivered(order) %></td>
          <td>
            <div class="tool">
              <% order.aasm.events.each do |event| %>
                <%# if event.to_s != 'atm_transfered' %>
                  <%= link_to get_event_display_name(event.to_s), "/admin/orders/#{order.id}/info_hub/#{event}" , class: "iframe uvs" %>
                <%# end %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>

    </table>
  </div>
</article>

<script type="text/javascript">
$(".show_order").click(function(){
  var $show_order = $("#show_order_" + $(this).data("order-id"))
  if( $show_order.length > 0 ){
    $show_order.stop().toggle();
    return false
  }
  else{
    return true;
  }
});
</script>

app/views/admin/orders/shipped.html.erb
<script src="/js_plugins/colorbox/jquery.colorbox-min.js"></script>
<link rel="stylesheet" type="text/css" href="/js_plugins/colorbox/colorbox.css" />    
<style>
div ,td, p .noTransition {
    -moz-transition: none;
    -webkit-transition: none;
    -o-transition: color 0 ease-in;
    transition: none;
}
</style>
<script>
  $(document).ready(function(){
    
    $(".iframe").colorbox({
      iframe:true, width:"483", height:"320",
      onClosed:function(){ parent.location.reload(); }
    });

  });
</script>

<header>
  <h2 class="left">訂單管理</h2>
  <nav class="left">
    <%= link_to "待付款", pending_admin_orders_path()  %>
    <%= link_to "需處理", admin_orders_path()%>
    <%= link_to "已出貨", shipped_admin_orders_path(), class: 'active' %>    
    <%= link_to "人為處理", human_involved_admin_orders_path()%>
    <%= link_to "歷史訂單", history_admin_orders_path()%>
  </nav>
</header>
<article>
  <div class="list">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th width="5%" align="center" class="icon"></th>
        <th width="12%" align="center"><%= sortable "payment_type", "付款方式" %></th>
        <th width="21%" align="left"><%= sortable "created_at", "訂單成立時間" %></th>
        <th width="16%" align="left"><%= sortable "ordernum", "編號" %></th>
        <th width="5%" align="center"><a href="javascript:void(0);">收款</a></th>
        <th width="5%" align="center"><a href="javascript:void(0);">出貨</a></th>
        <th width="30%"></th>
      </tr>

      <% @orders.each do |order| %>
        <tr id="order_<%= order.id %>">
          <td class="icon"></td>
          <td align="center"><%= order.get_payment_type %></td>
          <td><span class="time"><%= order.created_at.strftime("%Y-%m-%d %H:%M") %></span></td>
          <td><%= link_to order.ordernum, admin_order_path(order), :class => "show_order close", :remote => true, :data => { order_id: order.id } %></td>
          <td align="center"><%= is_order_paid(order) %></td>
          <td align="center"><%= is_order_delivered(order) %></td>
          <td>
            <div class="tool">
              <% order.aasm.events.each do |event| %>
                <%= link_to get_event_display_name(event.to_s), "/admin/orders/#{order.id}/info_hub/#{event}" , class: "iframe uvs" %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>

    </table>
  </div>
</article>

<script type="text/javascript">
$(".show_order").click(function(){
  var $show_order = $("#show_order_" + $(this).data("order-id"))
  if( $show_order.length > 0 ){
    $show_order.stop().toggle();
    return false
  }
  else{
    return true;
  }
});
</script>