config/routes.rb
Cama::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :admins, :path => 'camaadministrator', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  root "statics#index"

  get 'about' => 'statics#about', :as => :about
  
  resources :pages, :controller => :statics do 
    collection do
      get ':page', :action => :show, :as => :page
    end
  end
  
  resources :categories, :controller => :product_cates, :only => [ :index, :show] do 
    resources :products, :only => [:show]
  end
  # resources :product_cates, :only => [:index, :show] do
  #   resources :products, :only => [:show]
  # end

  resources :cart, :only => [:index, :create] do
    collection do
      get "check" => "cart#check" , :as => "check"
      get "final_check/" => "cart#final_check", :as => "final_check"
      get "finish"
      get "confirm" => "cart#confirm", :as => "confirm"
      #
      post "set_ship_to/:shipping_to" => "cart#set_ship_to" , :as => "set_ship_to"
      get "fail"
      #金流串接
      get "post_order/:id" => "cart#post_order", :as => "post_order"
      get "receive_result" => "cart#receive_result"

      match "add" => "cart#add" , :via => :post
    end

    member do
      match "plus/:index" => "cart#plus" , :via => :post , :as => "plus"
      match "minus/:index" => "cart#minus" , :via => :post , :as => "minus"
      match "delete_by_attribute/:index" => "cart#delete_by_attribute", :via => :post , :as => "delete_by_attribute"
      match "delete" => "cart#delete" , :via => :delete

    end
  end

  namespace :useradmin do
    
    resources :users, :only => [:index ,:update]
    resources :addressbooks , :only => [:index, :create, :destroy ,:update]
    
    
    resources :orders, :only => [:index, :show] do
      member do
        resources :orderasks, :only => [:new, :create]
        patch :atm_transfered #the only action that user allow to triggered
      end
    end
  
    root "orders#index"

  end

  resources :announcements , :only => [:index, :show]

  resources :talks , :only => [:index, :show] do 
    collection do 
      get 'about/:tag', to: 'talks#index', as: :about
    end
  end

  resources :stores do 
    collection do 
      get 'search', action: 'search'
    end
  end

  get 'fetch_from_country' => 'stores#fetch_from_country'
  get 'fetch_from_city' => 'stores#fetch_from_city'

  namespace :admin do

    authenticated :admin do
      root "orders#index"#, :as => :authenticated_root
    end

      mount RailsAdmin::Engine => '/advanced', as: 'rails_admin'
      
      resources :admins
      
      resources :product_cates, :except => [:new, :edit] do
        resources :products, :except => [:index, :new] do
          member do
            post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'

            get   '/basic_info'       => 'products#basic_info', as: 'basic_info'
            patch  '/basic_info'       => 'products#update_basic_info'

            get   '/free_paragraph'       => 'products#free_paragraph'
            post  '/free_paragraph'       => 'products#update'

            post 'create_product_attachment' , :action => 'create_product_attachment'
            post 'create_taste_attachment' , :action => 'create_taste_attachment'
          
            match :productphoto_upload, :via => :get
            match :taste_attributes, :via => :get

            match :change_status, :via => :post

            resources :product_stocks, :only => [:index, :create, :update, :destroy]
          end

          
        end

      end

      # resources :banners
      # #admin/index_sliders, admin/selected_products
      resources :index_sliders, controller: 'banners', type: 'IndexSlider' do
        # member do 
        #   # do or not?
        #   patch 'multiple_reorder' , :action => 'multiple_reorder'
        # end
      end

      resources :selected_products, controller: 'banners', type: 'SelectedProduct' do 
        # member do 
        #   # do or not?
        #   patch 'multiple_reorder' , :action => 'multiple_reorder'
        # end
      end

      resources :jobs 

      resources :stores do

        # edit
        member do 
          get 'fetch_from_country' , action: 'fetch_from_country'
          get 'fetch_from_city' , action: 'fetch_from_city'

          post 'create_store_attachment' , :action => 'create_store_attachment'
          match :storephoto_upload, :via => :get
        end

        # new
        collection do 
          get 'fetch_from_country' , action: 'fetch_from_country'
          get 'fetch_from_city' , action: 'fetch_from_city'
        end
      end

      resources :services do 
        member do 
          post 'create_service_attachment' , :action => 'create_service_attachment'
          match :servicephoto_upload, :via => :get        
        end      
      end

      resources :talks do 
        member do
          post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
          post 'create_talk_attachment' , :action => 'create_talk_attachment'
          match :talkphoto_upload, :via => :get        

          get   '/edit_tags'       => 'talks#edit_tags'
          patch  '/edit_tags'       => 'talks#update_tags'

        end
      end

      resources :announcements do 
        member do
          post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
          post 'create_announcement_attachment' , :action => 'create_announcement_attachment'
          match :announcementphoto_upload, :via => :get

          get '/custom_edit' => 'announcements#custom_edit'
          patch '/custom_edit' => 'announcements#update'

        end
      end

      resources :customizedpages do
        member do
          post 'create_customizedpage_attachment' , :action => 'create_customizedpage_attachment'
          match :customizedpagephoto_upload, :via => :get
        end
      end

      resources :galleries do 
        member do
          patch 'multiple_reorder' , :action => 'multiple_reorder'
        end 
      end


      resources :orders, :only => [:index, :show] do
        member do 
          #AASM
          post :checkout_succeeded_ATM # should remove
          post :cancel_before_paid_ATM
          post :atm_transfered
          post :money_placed_ATM
          post :atm_comfirmed
          
          post :checkout_succeeded_Vaccount # should remove
          post :cancel_before_paid_Vaccount
          post :comfirmed_Vaccount
          #post :human_involving_after_order_placed
          
          post :checkout_succeeded_COD # should remove
          post :shipping_COD
          post :post_collect_checked
          post :human_involving_after_order_placed_COD
          post :human_involving_post_collect_COD

          post :checkout_succeeded_general # should remove
          post :shipping_first
          post :human_involving_after_order_placed_general

          
          #SHARED
          post :checkout_failed # should remove
          post :shipping

          patch :shipping
          patch :shipping_first
          patch :shipping_COD
          patch :human_involving_after_order_placed_COD
          patch :human_involving_post_collect_COD
          patch :human_involving_after_order_placed_general
          patch :human_involving_after_money_placed
          patch :human_involving_after_money_checked
          patch :human_involving_after_shipped
          patch :human_involved_edit
          

          post :human_involved_edit
          post :human_involving_after_money_placed
          post :human_involving_after_money_checked
          post :human_involving_after_shipped
          post :close_deal
          post :to_abnormal

          get '/info_hub/:event' => 'orders#info_hub'
          post '/info_hub/:event' => 'orders#update_from_info_hub'

          get 'detail' => 'orders#detail'

        end

        collection do
          #金流：查詢交易狀態
          get "query_order_status/:id" => "orders#query_order_status", :as => "query_order"
          get "receive_order_status" => "orders#receive_order_status"

          get '/todolist' , action: 'index'
          get '/shipped' , action: 'shipped'
          get '/pending' , action: 'pending'
          get '/human_involved' , action: 'human_involved'
          #get '/history' , action: 'history'
          match 'history' => 'orders#history', via: [:get, :post], as: :history
          
        end

      end

      resources :orderasks, :only => [:index, :update] do
        collection do 
          get 'history', action: 'history'
        end
      end
      resources :users , :only => [:index, :show] do 
        collection do 
          get 'export', action: 'export'
          #get 'search', action: 'search'
        end
      end
      resources :deliveries

      delete 'peditor/deletePhoto/:id'        => 'peditor#destroyPhoto'
        
    

    #get '/camaadministrator/login' => 'devise/sessions#new'
    #unauthenticated :admin do
      #root to: redirect('/camaadministrator/login'), as: 'unauthenticated_root' # => "devise/sessions#new"
    #end
    
  end

  get '(*url)'   => 'errors#index'

end

app/models/customizedpage.rb
#encoding: utf-8
class Customizedpage < ActiveRecord::Base

  has_many :galleries, -> { order('ranking, created_at') } , as: :attachable , dependent: :destroy

  validates_presence_of :title
  
  before_validation :check_attrs
  
  def check_attrs
    self.title = "未命名文章" if self.title.blank?
    self.status = "disable" if self.status.blank?
  end
  
  def get_status
    case self.status
    when "disable"
      "下架"
    when "enable"
      "上架"
    end   
  end

  def is_available?
    self.status == "enable" ? true : false
  end

end

app/controllers/admin/customizedpages_controller.rb
#encoding: utf-8
class Admin::CustomizedpagesController < AdminController
  authorize_resource
  layout :resolve_layout

  before_action :set_customizedpage, only: [:show, :edit, :update, :destroy, :customizedpagephoto_upload, :create_customizedpage_attachment]

  def index

    @customizedpages = Customizedpage.all
    #@new_customizedpage = Customizedpage.new
  end
    
  def create

    @customizedpage = Customizedpage.create()
    #@customizedpage.article = Article.new

    respond_to do |format|
      if @customizedpage.save
        format.html { redirect_to customizedpagephoto_upload_admin_customizedpage_path(@customizedpage), notice: 'customizedpage was successfully created.' }
      else
        format.html { redirect_to :back, notice: @customizedpage.errors.full_messages }
      end
    end

  end

  def show
    
  end

  # GET /admin/customizedpages/1/edit
  def edit

  end

  # tab-2: customizedpage photo uploads
  def customizedpagephoto_upload
    
  end

  def create_customizedpage_attachment
      #deal with attachment
    if params[:filename].present? 
      display_name = params[:filename] 
    else 
      display_name = "#{@customizedpage.title}-CUSTOMIZEDPAGE-#{@customizedpage.galleries.count + 1}"
    end
    @latestAttach = CustomizedpageCoverGallery.create(:attachment => params[:attachment], :attachable => @customizedpage, :file_name => display_name) if params[:attachment]
    
    respond_to do |format|
       format.js {render :js => "window.location.href=window.location.href"}
    end
  end
  
  # PATCH/PUT /admin/customizedpages/1
  # PATCH/PUT /admin/customizedpages/1.json
  def update

    respond_to do |format|
      if @customizedpage.update(customizedpage_params)
        format.html { redirect_to admin_customizedpage_path(@customizedpage), notice: 'Customizedpage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: :back }
        format.json { render json: @customizedpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/customizedpages/1
  # DELETE /admin/customizedpages/1.json
  def destroy

    @customizedpage.destroy
    respond_to do |format|
      format.html { redirect_to admin_customizedpages_url }
      format.json { head :no_content }
    end
  end

  private

  def resolve_layout
    case action_name
    when "show"
      "customizedpage"
    else
      "admin"
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_customizedpage
    @customizedpage = Customizedpage.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customizedpage_params
    params.require(:customizedpage).permit(:title, :subtitle, :html_content, :js_content, :ranking)
  end


end

app/views/admin/customizedpages/_edit_tabs.html.erb
<%= link_to "封面上傳", customizedpagephoto_upload_admin_customizedpage_path(@customizedpage)%>|
<%= link_to "文章編輯", edit_admin_customizedpage_path(@customizedpage)%>

app/views/admin/customizedpages/customizedpagephoto_upload.html.erb
<%= render 'edit_tabs' %>
<header>
  <h2 class="left">自訂頁面/封面上傳</h2>
  <nav class="left"></nav>
</header>

<div id="attach_form_container">
    <div id="createNewAttach" >
        <%= form_for(@customizedpage,url: create_customizedpage_attachment_admin_customizedpage_path(id: params[:id]) , :html => {:id =>'NewAttachlForm' , :method => "POST", :remote => true} ) do |fattach| %>
          <div class='errors'></div>
            <div class="form">
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td width="7%">檔案：</td>
                  <td width="55%"><%= file_field_tag :attachment , class: 'file' %></td>
                </tr>
              </table>
            </div>
        </div>
    </div>

<div class='button'>
<%= fattach.submit '上傳' , class: 'right highlight' ,style: 'width:125px' %>
</div>

<% end %>       <!--form end-->

<div class="list">
<table id="mainAttachList"  width="100%" border="0" cellspacing="0" cellpadding="0" >
    <tbody id="listThisAttach">
        <% @customizedpage.galleries.select{ |v| v['type'] == "CustomizedpageCoverGallery" }.each do |attach| %>
            <tr <%= "id=createAttachcontainer_#{attach.id.to_s}" %> class="createAttachcontainer dragable" >
              <td width="6%"></td>
              <td width="12%"><img src=<%= "#{attach.attachment.url}" %> alt=<%= "#{attach.file_name}" %> width="85%" height="auto"/></td>
              <td width="64%"><%= (attach.file_size.to_i)/1000 %>KB @ [<%= attach.updated_at.in_time_zone("Taipei") %> 上傳] </td>
              <td width="18%">
                <div class="tool">
                    <%= link_to '刪除', admin_gallery_path(attach.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete', title: '刪除' %>
                </div>
               </td>
             </tr>
        <% end %>
    </tbody>
  </table>
</div>

<script>
$(function() {
      var prevEvent = null;
        $( "#listThisAttach" ).sortable({
          //connectWith: ".renamelevelcontainer",
          items: "> .dragable" ,
          placeholder: "ui-state-highlight",
          update: function( event, ui ) {
              
          if(event.timeStamp == prevEvent){
            return null;
          }
          
          prevEvent = event.timeStamp;  
          var newRankings_array = $('#listThisAttach').sortable('toArray');
          var orderSet = [];
          $.each(newRankings_array, function( index, value){
                orderSet.push(value.replace("createAttachcontainer_",""));
            });
            var order2Push = JSON.stringify(orderSet);
            
            $.ajaxSetup({
              headers: {
                  'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            }
          });

              //multiple reorder 
              $.ajax({
                type: "PATCH",
                url: "/admin/galleries/"+orderSet[0]+"/multiple_reorder",
                data: { gallerries: {  reorderset: orderSet } },
                success: function(data){
               //alert ("success");
                  //console.log("================ customizedpages reorder PATCH successfully end =============");
                  return false   
                },
                error: function(data){
                //alert ("faild");
                  //console.log("================ customizedpages reorder has some issues ==================");
                  return false  
                }
              });

          }
        });
        
          
        $( "#listThisAttach" ).disableSelection();
      });  
    //################################ attachment reorder end #######################################
</script>

app/views/admin/customizedpages/edit.html.erb
<%= render 'edit_tabs' %>
<%= form_for(@customizedpage, :url => admin_customizedpage_path(@customizedpage), html: { id: "patchthiscustomizedpage" } ) do |f| %>
  <table>
    <tr>
      <td>
      NAME:<br><%= f.text_field :title %>
      </td>
      <td style="text-align:right;">
      [ <%= f.submit "送出" %> ]
      </td>
     
    </tr>
    <tr>
      <td width:45%>
      JS(insert into head):<br><%= f.text_area(:js_content, size: '80x50') %><br>
      </td>

      <td width:45% >
      HTML(insert into body):<br><%= f.text_area(:html_content, size: '80x50') %><br>
      </td>
     
    </tr>

<% end %>

app/views/admin/customizedpages/index.html.erb
<h3>自訂頁面/文章列表</h3>

<%= link_to("新增頁面", admin_customizedpages_path(), :method => :post) %>

<table border="0" cellspacing="0" cellpadding="3">
  <% @customizedpages.each do |customizedpage| %>
  <tr>
    <td><%# customizedpage.get_status %></td>
    <td><%= link_to(customizedpage.title, admin_customizedpage_path(customizedpage)) %></td>
    <td>
      <%# link_to(get_change_status_name(customizedpage), change_status_admin_customizedpage_cate_customizedpage_path(@customizedpage_cate, customizedpage), :method => :post) %>

      <%# customizedpages_helper %>
      <%# link_to("編輯", edit_admin_customizedpage_cate_customizedpage_path(@customizedpage_cate, customizedpage)) %>
      <%= link_to("編輯", edit_admin_customizedpage_path(customizedpage)) %>
      <%= link_to("刪除", admin_customizedpage_path(customizedpage), :method => :delete, :data => {:confirm => "確定刪除？"}) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin/customizedpages/show.html.erb
<% content_for :head do %>
  <%= @customizedpage.js_content.html_safe %>    
<% end %>

<%= @customizedpage.html_content.html_safe %>

<table id="mainAttachList"  width="100%" border="0" cellspacing="0" cellpadding="0" >
  <tbody id="listThisAttach">

      <% @customizedpage.galleries.select{ |v| v['type'] == "CustomizedpageCoverGallery" }.each do |attach| %>
          <tr <%= "id=createAttachcontainer_#{attach.id.to_s}" %> class="createAttachcontainer dragable" >
            <td width="12%"><img width="30%" height="auto" src=<%= "#{attach.attachment.url}" %> alt=<%= "#{attach.file_name}" %>/></td>
           </tr>
      <% end %>

  </tbody>
</table>