config/routes.rb
Cama::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :admins, :path => 'camaadministrator', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  root "statics#index"

  get 'about' => 'statics#about', :as => :about
  
  resources :pages, :controller => :statics do 
    collection do
      get ':page', :action => :show, :as => :page
    end
  end
  
  resources :categories, :controller => :product_cates, :only => [ :index, :show] do 
    resources :products, :only => [:show]
  end
  # resources :product_cates, :only => [:index, :show] do
  #   resources :products, :only => [:show]
  # end

  resources :cart, :only => [:index, :create] do
    collection do
      get "check" => "cart#check" , :as => "check"
      get "final_check/" => "cart#final_check", :as => "final_check"
      get "finish"
      get "confirm" => "cart#confirm", :as => "confirm"
      #
      post "set_ship_to/:shipping_to" => "cart#set_ship_to" , :as => "set_ship_to"
      get "fail"
      #金流串接
      get "post_order/:id" => "cart#post_order", :as => "post_order"
      get "receive_result" => "cart#receive_result"

      match "add" => "cart#add" , :via => :post
    end

    member do
      match "plus/:index" => "cart#plus" , :via => :post , :as => "plus"
      match "minus/:index" => "cart#minus" , :via => :post , :as => "minus"
      match "delete_by_attribute/:index" => "cart#delete_by_attribute", :via => :post , :as => "delete_by_attribute"
      match "delete" => "cart#delete" , :via => :delete

    end
  end

  namespace :useradmin do
    
    resources :users, :only => [:index ,:update]
    resources :addressbooks , :only => [:index, :create, :destroy ,:update]
    
    
    resources :orders, :only => [:index, :show] do
      member do
        resources :orderasks, :only => [:new, :create]
        patch :atm_transfered #the only action that user allow to triggered
      end
    end
  
    root "orders#index"

  end

  resources :announcements , :only => [:index, :show]

  resources :talks , :only => [:index, :show] do 
    collection do 
      get 'about/:tag', to: 'talks#index', as: :about
    end
  end

  resources :stores do 
    collection do 
      get 'search', action: 'search'
    end
  end

  get 'fetch_from_country' => 'stores#fetch_from_country'
  get 'fetch_from_city' => 'stores#fetch_from_city'

  namespace :admin do

    authenticated :admin do
      root "orders#index"#, :as => :authenticated_root
    end

      mount RailsAdmin::Engine => '/advanced', as: 'rails_admin'
      
      resources :admins
      
      resources :product_cates, :except => [:new, :edit] do
        resources :products, :except => [:index, :new] do
          member do
            post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'

            get   '/basic_info'       => 'products#basic_info', as: 'basic_info'
            patch  '/basic_info'       => 'products#update_basic_info'

            get   '/free_paragraph'       => 'products#free_paragraph'
            post  '/free_paragraph'       => 'products#update'

            post 'create_product_attachment' , :action => 'create_product_attachment'
            post 'create_taste_attachment' , :action => 'create_taste_attachment'
          
            match :productphoto_upload, :via => :get
            match :taste_attributes, :via => :get

            match :change_status, :via => :post

            resources :product_stocks, :only => [:index, :create, :update, :destroy]
          end

          
        end

      end

      # resources :banners
      # #admin/index_sliders, admin/selected_products
      resources :index_sliders, controller: 'banners', type: 'IndexSlider' do
        # member do 
        #   # do or not?
        #   patch 'multiple_reorder' , :action => 'multiple_reorder'
        # end
      end

      resources :selected_products, controller: 'banners', type: 'SelectedProduct' do 
        # member do 
        #   # do or not?
        #   patch 'multiple_reorder' , :action => 'multiple_reorder'
        # end
      end

      resources :jobs 

      resources :stores do

        # edit
        member do 
          get 'fetch_from_country' , action: 'fetch_from_country'
          get 'fetch_from_city' , action: 'fetch_from_city'

          post 'create_store_attachment' , :action => 'create_store_attachment'
          match :storephoto_upload, :via => :get
        end

        # new
        collection do 
          get 'fetch_from_country' , action: 'fetch_from_country'
          get 'fetch_from_city' , action: 'fetch_from_city'
        end
      end

      resources :services do 
        member do 
          post 'create_service_attachment' , :action => 'create_service_attachment'
          match :servicephoto_upload, :via => :get        
        end      
      end

      resources :talks do 
        member do
          post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
          post 'create_talk_attachment' , :action => 'create_talk_attachment'
          match :talkphoto_upload, :via => :get        

          get   '/edit_tags'       => 'talks#edit_tags'
          patch  '/edit_tags'       => 'talks#update_tags'

        end
      end

      resources :announcements do 
        member do
          post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
          post 'create_announcement_attachment' , :action => 'create_announcement_attachment'
          match :announcementphoto_upload, :via => :get

          get '/custom_edit' => 'announcements#custom_edit'
          patch '/custom_edit' => 'announcements#update'

        end
      end

      resources :customizedpages do
        member do
          post 'create_customizedpage_attachment' , :action => 'create_customizedpage_attachment'
          match :customizedpagephoto_upload, :via => :get
        end
      end

      resources :galleries do 
        member do
          patch 'multiple_reorder' , :action => 'multiple_reorder'
        end 
      end


      resources :orders, :only => [:index, :show] do
        member do 
          #AASM
          post :checkout_succeeded_ATM # should remove
          post :cancel_before_paid_ATM
          post :atm_transfered
          post :money_placed_ATM
          post :atm_comfirmed
          
          post :checkout_succeeded_Vaccount # should remove
          post :cancel_before_paid_Vaccount
          post :comfirmed_Vaccount
          #post :human_involving_after_order_placed
          
          post :checkout_succeeded_COD # should remove
          post :shipping_COD
          post :post_collect_checked
          post :human_involving_after_order_placed_COD
          post :human_involving_post_collect_COD

          post :checkout_succeeded_general # should remove
          post :shipping_first
          post :human_involving_after_order_placed_general

          
          #SHARED
          post :checkout_failed # should remove
          post :shipping

          patch :shipping
          patch :shipping_first
          patch :shipping_COD
          patch :human_involving_after_order_placed_COD
          patch :human_involving_post_collect_COD
          patch :human_involving_after_order_placed_general
          patch :human_involving_after_money_placed
          patch :human_involving_after_money_checked
          patch :human_involving_after_shipped
          patch :human_involved_edit
          

          post :human_involved_edit
          post :human_involving_after_money_placed
          post :human_involving_after_money_checked
          post :human_involving_after_shipped
          post :close_deal
          post :to_abnormal

          get '/info_hub/:event' => 'orders#info_hub'
          post '/info_hub/:event' => 'orders#update_from_info_hub'

          get 'detail' => 'orders#detail'

        end

        collection do
          #金流：查詢交易狀態
          get "query_order_status/:id" => "orders#query_order_status", :as => "query_order"
          get "receive_order_status" => "orders#receive_order_status"

          get '/todolist' , action: 'index'
          get '/shipped' , action: 'shipped'
          get '/pending' , action: 'pending'
          get '/human_involved' , action: 'human_involved'
          #get '/history' , action: 'history'
          match 'history' => 'orders#history', via: [:get, :post], as: :history
          
        end

      end

      resources :orderasks, :only => [:index, :update] do
        collection do 
          get 'history', action: 'history'
        end
      end
      resources :users , :only => [:index, :show] do 
        collection do 
          get 'export', action: 'export'
          #get 'search', action: 'search'
        end
      end
      resources :deliveries

      delete 'peditor/deletePhoto/:id'        => 'peditor#destroyPhoto'
        
    

    #get '/camaadministrator/login' => 'devise/sessions#new'
    #unauthenticated :admin do
      #root to: redirect('/camaadministrator/login'), as: 'unauthenticated_root' # => "devise/sessions#new"
    #end
    
  end

  get '(*url)'   => 'errors#index'

end

app/controllers/admin/stores_controller.rb
#encoding: utf-8
class Admin::StoresController < AdminController
  authorize_resource
  ###################
  # ref count not implement yet
  ###################
  helper_method :sort_column, :sort_direction
  
  before_action :set_store, only: [:show, :edit, :update, :destroy, :storephoto_upload, :create_store_attachment]

  def index
    # tagged_with example
    
    #指定特別 tag分類
    #@stores = Store.tagged_with(["台中市","台北市"], on: :locations, any: true)
    #不指定特別 tag分類
    #@stores = Store.tagged_with(["台中市","台北市"], any: true)
    #其他屬性(can work with pre-defined scope and paginate)
    # :match_all => true , :exclude => true, 
    #You can also use :wild => true option along with :any or :exclude option. It will be looking for %awesome% and %cool% in SQL
    #find_related_skills

    #@stores = Store.all

    @stores = Store.order(sort_column + " " + sort_direction).page(params[:page])
    #@store = Store.new
  end

  def new
    @store = Store.new

    @countries = Country.all #use it when country selectable
    @cities = City.where("country_id = ?", Country.first.id)
    @districts = District.where("city_id = ?", City.first.id)

  end
    
  def create

    @store = Store.new(store_params)
    #let location as default tagged
    @store.location_list.add(Country.find(@store.country).name) unless @store.country.empty?
    @store.location_list.add(City.find(@store.city).name) unless @store.city.empty?
    @store.location_list.add(District.find(@store.district).name) unless @store.district.empty?

    respond_to do |format|
      if @store.save
        format.html { redirect_to admin_stores_path(), notice: 'store was successfully created.' }
      else
        format.html { redirect_to :back, notice: @store.errors.full_messages }
      end
    end

  end

  def show

  end

  # GET /admin/stores/1/edit
  def edit
    
    @cities = City.where("country_id = ?", @store.country)
    @districts = District.where("city_id = ?", @store.city)
    #get all tag by context
    #@all_tag_with_context = ActsAsTaggableOn::Tagging.where(:context => 'services').joins(:tag).select('DISTINCT tags.name').map{ |x| x.name}

  end

  # tab-2: store photo uploads
  def storephoto_upload
    @gallery_count = @store.galleries.select{ |v| v['type'] == "StorePhotoGallery" }.count
  end

  def create_store_attachment
      #deal with attachment
    if params[:filename].present? 
      display_name = params[:filename] 
    else 
      display_name = "#{@store.name}-STORE-#{@store.galleries.count + 1}"
    end
    @latestAttach = StorePhotoGallery.create(:attachment => params[:attachment], :attachable => @store, :file_name => display_name) if params[:attachment]
    
    respond_to do |format|
       format.html { redirect_to storephoto_upload_admin_store_path(@store), notice: 'store photo was successfully created.' }
       #format.js {render :js => "window.location.href=window.location.href"}
    end
  end

  def fetch_from_country
    @cities = City.where("country_id = ?", params[:country_id])
    @districts = District.where("city_id = ?", @cities.first.id)
    respond_to do |format|
      format.js
    end    
  end

  def fetch_from_city 
    @districts = District.where("city_id = ?", params[:city_id])
    respond_to do |format|
      format.js
    end    
  end


  # PATCH/PUT /admin/stores/1
  # PATCH/PUT /admin/stores/1.json
  def update

    @store.location_list = ""
    #p store_params[:location_list]
    
    @store.location_list.add(Country.find(@store.country).name) unless @store.country.empty?
    @store.location_list.add(City.find(@store.city).name) unless @store.city.empty?
    @store.location_list.add(District.find(@store.district).name) unless @store.district.empty?

    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to :back, notice: '更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: :back }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/stores/1
  # DELETE /admin/stores/1.json
  def destroy

    #也要處理相關tags的刪除？

    @store.destroy
    respond_to do |format|
      format.html { redirect_to admin_stores_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def store_params
    params.require(:store).permit(:name, :address, :intro, :phone, :address, :country, :city, :district, :ophour, :latlng, :location_list , :service_list )
  end

  def sort_column
    Store.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/controllers/stores_controller.rb
#encoding: utf-8
class StoresController < ApplicationController
  helper_method :sort_column, :sort_direction
  
  before_action :set_store, only: [:show]

  def index

    @countries = Country.all #use it when country selectable
    @cities = City.where("country_id = ?", Country.first.id)
    @districts = District.where("city_id = ?", City.first.id)
    #@stores = Store.order(sort_column + " " + sort_direction).page(params[:page])
    @services = Service.includes(:galleries).all
  end
  
  def search 
    #need to check params is valid
    if params[:look_for_services]
      # search services use IN condition
      #@stores = Store.includes(:services).where(country: params[:country], city: params[:city], district: params[:district],:services => {:id => params[:look_for_services]})
      
      # search services use AND condition
      match_ids = (StoreServiceShip.where(service_id: params[:look_for_services]).select('store_id').group('store_id').count).select {|k,v| v == params[:look_for_services].length }
      
      unless params[:district].empty? || params[:district].nil?
        @stores = Store.where(id: match_ids.keys ,country: params[:country], city: params[:city], district: params[:district])
      else
        @stores = Store.where(id: match_ids.keys ,country: params[:country], city: params[:city])
      end
        
    else
      unless params[:district].empty? || params[:district].nil?
        @stores = Store.where(country: params[:country], city: params[:city], district: params[:district])
      else
        @stores = Store.where(country: params[:country], city: params[:city])
      end
      #@stores = Store.where(country: params[:country], city: params[:city], district: params[:district])
    end

    respond_to do |format|
      format.js
    end    

  end

  def show
    #service

  end

  def fetch_from_country
    @cities = City.where("country_id = ?", params[:country_id])
    @districts = District.where("city_id = ?", @cities.first.id)
    respond_to do |format|
      format.js
    end    
  end

  def fetch_from_city 
    @districts = District.where("city_id = ?", params[:city_id])
    respond_to do |format|
      format.js
    end    
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store
    begin
      @store = Store.friendly.find(params[:id])

      if request.path.downcase != store_path(@store).downcase
        return redirect_to @store, :status => :moved_permanently
      end
    rescue
      #flash[:notice] = "文章不存在"
      redirect_to announcements_path and return
    end

  end

  def sort_column
    Store.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/views/admin/stores/_edit_tabs.html.erb
<%= link_to "分店資料", edit_admin_store_path(@store)%>|
<%= link_to "分店圖片", storephoto_upload_admin_store_path(@store)%>

app/views/admin/stores/edit.html.erb
<header>
  <h2 class="left">門市資訊<span>/ 分店管理</span></h2>  
  <nav class="left">
    <a href="javascript:void(0);" class="active">簡介</a>
    <%= link_to "照片", storephoto_upload_admin_store_path(@store)%>
  </nav>
</header>
<article>
  <div class="form">
    <%= form_for @store, :url => admin_store_path(@store), html: {method: "patch" , id: "patchthisstore"} do |f| %>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="7%">門市：</td>
        <td width="42%"><%= f.text_field :name , class: "text" %></td>
        <td width="2%"></td>
        <td width="7%">電話：</td>
        <td width="42%"><%= f.text_field :phone , class: "text" %></td>
      </tr>
      <tr>
        <td valign="top" style="padding:13px 0 0 0">地址：</td>
        <td colspan="4">
          <%= f.hidden_field :country , value: 1 %>         
          <%= f.select :city, options_for_select(@cities.collect { |city|
            [city.name, city.id] }, @store.city), {}, { id: 'cities_select', style: "width:14%" } %>
          <%= f.select :district, options_for_select(@districts.collect { |district|
            [district.name, district.id] }, @store.district), {}, { id: 'districts_select', style: "width:14%" } %><br>
            <%= f.text_field :address ,class: "text", placeholder:"請輸入完整地址"%>
          </td>
      </tr>
      <tr>
        <td>時間：</td>
        <td colspan="4"><%= f.text_area :ophour, cols: "", rows:"" %></td>
      </tr>
      <tr>
        <td>標籤：</td>
        <td colspan="4">
          <%= f.text_field :service_list, id: "service_item_field" , class: "tag-text" %>
        </td>
      </tr>
      <tr>
        <td valign="top">簡介：</td>
        <td colspan="4"><%= f.text_area :intro, cols: "", rows:"" %> </td>
      </tr>
      <tr>
        <td>地圖：</td>
        <td colspan="4"><%= f.text_field :latlng,class: "text" %> </td>
      </tr>
    </table>
    <% end %>
  </div>
  <!--form-->

  <div class="button"> 
    <%= link_to image_tag("/images/admin/left.png")+"返回", admin_stores_path(), class: "left" %>
    <a href="javascript: document.getElementById('patchthisstore').submit();" class="right highlight" data-no-turbolink = true >儲存<img src="<%= image_path("save.png") %>"></a>
  </div>
  
</article>

<script type="text/javascript">

$("#service_item_field").select2({

    tags: <%= Service.all.map { |service|
    service.name }.to_s.html_safe %>,
    tokenSeparators: [",", " "]
});

</script>

app/views/admin/stores/index.html.erb
<header>
  <h2 class="left">門市資訊<span>/ 分店管理</span></h2>
</header>
<article>
  <div class="button">
    <%= link_to new_admin_store_path(), :method => :get,class: "right highlight"  do %>
      新增門市<img src="/images/admin/add.png">
    <% end %>
  </div>
  <div class="list">
  <%#sortable "name", "店名" %>  <%# sortable "city" , "城市" %>  <%# sortable "address" , "地址" %>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <% @stores.each do |store| %>
      <tr>
        <td width="70%">
          <%= link_to "#{store.name}", store_path(store), target: '_blank' %>
        </td>
        <td width="18%"><%= City.find(store.city).name %> / <%= District.find(store.district).name %></td>
        <td width="12%">
          <div class="tool">
            <%= link_to "", edit_admin_store_path(store), class: "edit" %>
            <%= link_to "", admin_store_path(store), :data => { :confirm => "將會刪除此門市，確定繼續？" }, :method => :delete, :class => "delete", title: "刪除" %>
          </div>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <div class= "page">
    <%= paginate @stores ,:window => 2 %>
  </div>
</article>

app/views/admin/stores/new.html.erb
<header>
  <h2 class="left">門市資訊<span>/ 分店管理</span></h2>
  <nav class="left">
    <a href="javascript:void(0);" class="active">簡介</a>
    <%# link_to "照片", storephoto_upload_admin_store_path(@store)%>
  </nav>
</header>
<article>
  <div class="form">
    <%= form_for @store, :url => admin_stores_path(@store), html: { id: "create_this_store",method: "post"} do |f| %>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="7%">門市：</td>
        <td width="42%"><%= f.text_field :name , class: "text" %></td>
        <td width="2%"></td>
        <td width="7%">電話：</td>
        <td width="42%"><%= f.text_field :phone , class: "text" %></td>
      </tr>
      <tr>
        <td valign="top" style="padding:13px 0 0 0">地址：</td>
        <td colspan="4">
            <%= f.hidden_field :country , value: 1 %>   
            <%# f.select :country, options_for_select(@countries.collect { |country|
        [country.name, country.id] }, 1), {}, { id: 'countries_select', style: "width:14%" } %>
            <%= f.select :city, options_for_select(@cities.collect { |city|
              [city.name, city.id] }, 1), {}, { id: 'cities_select', style: "width:14%" } %>
            <%= f.select :district, options_for_select(@districts.collect { |district|
              [district.name, district.id] }, 0), {}, { id: 'districts_select' , style: "width:14%"} %>

          <%# f.hidden_field :country , value: 1 %>   

          <%# f.select :city, options_for_select(@cities.collect { |city|
            [city.name, city.id] }, @store.city), {}, { id: 'cities_select', style: "width:14%" } %>
          <%# f.select :district, options_for_select(@districts.collect { |district|
            [district.name, district.id] }, @store.district), {}, { id: 'districts_select', style: "width:14%" } %><br>
            <%= f.text_field :address ,class: "text", placeholder:"請輸入完整地址"%>
          </td>
      </tr>
      <tr>
        <td>時間：</td>
        <td colspan="4"><%= f.text_area :ophour, cols: "", rows:"" %></td>
      </tr>
      <tr>
        <td>標籤：</td>
        <td colspan="4">
          <%= f.text_field :service_list, id: "service_item_field" , class: "tag-text" %>
        </td>
      </tr>
      <tr>
        <td valign="top">簡介：</td>
        <td colspan="4"><%= f.text_area :intro, name: "", cols: "", rows:"" %> </td>
      </tr>
      <tr>
        <td>地圖：</td>
        <td colspan="4"><%= f.text_field :latlng,class: "text" %> </td>
      </tr>
    </table>
    <% end %>
  </div>
  <!--form-->

  <div class="button"> 
    <%= link_to image_tag("/images/admin/left.png")+"返回", admin_stores_path(), class: "left" %>
    <a href="javascript: document.getElementById('create_this_store').submit();" class="right highlight" data-no-turbolink = true >儲存<img src="<%= image_path("save.png") %>"></a>
  </div>
  
</article>

<script type="text/javascript">

$("#service_item_field").select2({

    tags: <%= Service.all.map { |service|
    service.name }.to_s.html_safe %>,
    tokenSeparators: [",", " "]
});

</script>

app/views/admin/stores/storephoto_upload.html.erb
<style>
div ,td, p .noTransition {
    -moz-transition: none;
    -webkit-transition: none;
    -o-transition: color 0 ease-in;
    transition: none;
}
</style>
<header>
  <h2 class="left">門市資訊<span>/ 分店管理</span></h2>
  <nav class="left">
    <%= link_to "簡介", edit_admin_store_path(@store)%>
    <a href="javascript:void(0);" class="active">照片</a>
  </nav>
  <div class="explain right"><p>圖片尺寸：609 px * 406 px</p></div>
</header>
<article>
  <% if @gallery_count < 5 %>

  <div class="form">
    <%= form_for(@store,url: create_store_attachment_admin_store_path(@store) , :html => {:id =>'NewAttachlForm' , :method => "POST", :multipart => true} ) do |fattach| %>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="7%">圖片：</td>
          <td width="93%"><%= file_field_tag :attachment , class: 'file' %></td>
        </tr>
      </table>
   <% end %>  
  </div>

  <div class="button">
    <a href="javascript: document.getElementById('NewAttachlForm').submit();" class="right highlight" data-no-turbolink = true >上傳
      <img src="<%= image_path("/images/admin/up.png") %>">
    </a>
  </div>
  
  <% end %>
  <div class="hgroup">
    <h3 class="left">圖片預覽<span>(可拖拉排序，第一張為封面)</span></h3>          
  </div>
  <div class="gallery" id="listThisAttach">

    <% @store.galleries.select{ |v| v['type'] == "StorePhotoGallery" }.each_with_index do |attach, i| %>
      <% if i == 0 %>
        <div class="thumb left cover createAttachcontainer dragable" <%= "id=createAttachcontainer_#{attach.id.to_s}" %>> 
      <% else %>
        <div class="thumb left createAttachcontainer dragable" <%= "id=createAttachcontainer_#{attach.id.to_s}" %>> 
      <% end %>
      
        <%= link_to '', admin_gallery_path(attach.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete', title: '刪除' %>
        <img src=<%= "#{attach.attachment.url}" %> />
      </div>
    <% end %>

  </div>
</article>

<script>
$(function() {
  var prevEvent = null;
    $( "#listThisAttach" ).sortable({
      //connectWith: ".renamelevelcontainer",
      items: "> .dragable" ,
      placeholder: "ui-state-highlight",
      update: function( event, ui ) {
          
      if(event.timeStamp == prevEvent){
        return null;
      }
      
      prevEvent = event.timeStamp;  
      var newRankings_array = $('#listThisAttach').sortable('toArray');
      var orderSet = [];
      $.each(newRankings_array, function( index, value){
            orderSet.push(value.replace("createAttachcontainer_",""));
        });
        var order2Push = JSON.stringify(orderSet);
        
        $.ajaxSetup({
          headers: {
              'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        }
      });

          //multiple reorder 
          $.ajax({
            type: "PATCH",
            url: "/admin/galleries/"+orderSet[0]+"/multiple_reorder",
            data: { gallerries: {  reorderset: orderSet } },
            success: function(data){

              $("#listThisAttach > .thumb").attr('class', 'thumb left createAttachcontainer dragable');
              $("#listThisAttach > .thumb:first").attr('class', 'cover thumb left createAttachcontainer dragable');
              alertify['success'](data[0][1], 2000);
              //console.log("================ stores reorder PATCH successfully end =============");
              return false   
            },
            error: function(data){
            //alert ("faild");
              //console.log("================ stores reorder has some issues ==================");
              return false  
            }
          });

      }
    });
    
      
    $( "#listThisAttach" ).disableSelection();
  });  
//################################ attachment reorder end #######################################
</script>

app/views/admin/stores/x_show.html.erb
Store show<br>


<%= @store.name %><br>
<%= @store.intro %><br>
<%= @store.phone %><br>
<%= @store.address %><br>
<%= @store.country %> <%= @store.city %> <%= @store.district %><br>
<%= @store.ophour %><br>
<%= @store.latlng.html_safe %><br>
<%= @store.location_list %><br>

<br><br><br><br>
<%= link_to "GO BACK", admin_stores_path %>