config/routes.rb
Cama::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :admins, :path => 'camaadministrator', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  root "statics#index"

  get 'about' => 'statics#about', :as => :about
  
  resources :pages, :controller => :statics do 
    collection do
      get ':page', :action => :show, :as => :page
    end
  end
  
  resources :categories, :controller => :product_cates, :only => [ :index, :show] do 
    resources :products, :only => [:show]
  end
  # resources :product_cates, :only => [:index, :show] do
  #   resources :products, :only => [:show]
  # end

  resources :cart, :only => [:index, :create] do
    collection do
      get "check" => "cart#check" , :as => "check"
      get "final_check/" => "cart#final_check", :as => "final_check"
      get "finish"
      get "confirm" => "cart#confirm", :as => "confirm"
      #
      post "set_ship_to/:shipping_to" => "cart#set_ship_to" , :as => "set_ship_to"
      get "fail"
      #金流串接
      get "post_order/:id" => "cart#post_order", :as => "post_order"
      get "receive_result" => "cart#receive_result"

      match "add" => "cart#add" , :via => :post
    end

    member do
      match "plus/:index" => "cart#plus" , :via => :post , :as => "plus"
      match "minus/:index" => "cart#minus" , :via => :post , :as => "minus"
      match "delete_by_attribute/:index" => "cart#delete_by_attribute", :via => :post , :as => "delete_by_attribute"
      match "delete" => "cart#delete" , :via => :delete

    end
  end

  namespace :useradmin do
    
    resources :users, :only => [:index ,:update]
    resources :addressbooks , :only => [:index, :create, :destroy ,:update]
    
    
    resources :orders, :only => [:index, :show] do
      member do
        resources :orderasks, :only => [:new, :create]
        patch :atm_transfered #the only action that user allow to triggered
      end
    end
  
    root "orders#index"

  end

  resources :announcements , :only => [:index, :show]

  resources :talks , :only => [:index, :show] do 
    collection do 
      get 'about/:tag', to: 'talks#index', as: :about
    end
  end

  resources :stores do 
    collection do 
      get 'search', action: 'search'
    end
  end

  get 'fetch_from_country' => 'stores#fetch_from_country'
  get 'fetch_from_city' => 'stores#fetch_from_city'

  namespace :admin do

    authenticated :admin do
      root "orders#index"#, :as => :authenticated_root
    end

      mount RailsAdmin::Engine => '/advanced', as: 'rails_admin'
      
      resources :admins
      
      resources :product_cates, :except => [:new, :edit] do
        resources :products, :except => [:index, :new] do
          member do
            post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'

            get   '/basic_info'       => 'products#basic_info', as: 'basic_info'
            patch  '/basic_info'       => 'products#update_basic_info'

            get   '/free_paragraph'       => 'products#free_paragraph'
            post  '/free_paragraph'       => 'products#update'

            post 'create_product_attachment' , :action => 'create_product_attachment'
            post 'create_taste_attachment' , :action => 'create_taste_attachment'
          
            match :productphoto_upload, :via => :get
            match :taste_attributes, :via => :get

            match :change_status, :via => :post

            resources :product_stocks, :only => [:index, :create, :update, :destroy]
          end

          
        end

      end

      # resources :banners
      # #admin/index_sliders, admin/selected_products
      resources :index_sliders, controller: 'banners', type: 'IndexSlider' do
        # member do 
        #   # do or not?
        #   patch 'multiple_reorder' , :action => 'multiple_reorder'
        # end
      end

      resources :selected_products, controller: 'banners', type: 'SelectedProduct' do 
        # member do 
        #   # do or not?
        #   patch 'multiple_reorder' , :action => 'multiple_reorder'
        # end
      end

      resources :jobs 

      resources :stores do

        # edit
        member do 
          get 'fetch_from_country' , action: 'fetch_from_country'
          get 'fetch_from_city' , action: 'fetch_from_city'

          post 'create_store_attachment' , :action => 'create_store_attachment'
          match :storephoto_upload, :via => :get
        end

        # new
        collection do 
          get 'fetch_from_country' , action: 'fetch_from_country'
          get 'fetch_from_city' , action: 'fetch_from_city'
        end
      end

      resources :services do 
        member do 
          post 'create_service_attachment' , :action => 'create_service_attachment'
          match :servicephoto_upload, :via => :get        
        end      
      end

      resources :talks do 
        member do
          post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
          post 'create_talk_attachment' , :action => 'create_talk_attachment'
          match :talkphoto_upload, :via => :get        

          get   '/edit_tags'       => 'talks#edit_tags'
          patch  '/edit_tags'       => 'talks#update_tags'

        end
      end

      resources :announcements do 
        member do
          post  'peditor/:id/createPhoto'       => 'peditor#createPhoto'
          post 'create_announcement_attachment' , :action => 'create_announcement_attachment'
          match :announcementphoto_upload, :via => :get

          get '/custom_edit' => 'announcements#custom_edit'
          patch '/custom_edit' => 'announcements#update'

        end
      end

      resources :customizedpages do
        member do
          post 'create_customizedpage_attachment' , :action => 'create_customizedpage_attachment'
          match :customizedpagephoto_upload, :via => :get
        end
      end

      resources :galleries do 
        member do
          patch 'multiple_reorder' , :action => 'multiple_reorder'
        end 
      end


      resources :orders, :only => [:index, :show] do
        member do 
          #AASM
          post :checkout_succeeded_ATM # should remove
          post :cancel_before_paid_ATM
          post :atm_transfered
          post :money_placed_ATM
          post :atm_comfirmed
          
          post :checkout_succeeded_Vaccount # should remove
          post :cancel_before_paid_Vaccount
          post :comfirmed_Vaccount
          #post :human_involving_after_order_placed
          
          post :checkout_succeeded_COD # should remove
          post :shipping_COD
          post :post_collect_checked
          post :human_involving_after_order_placed_COD
          post :human_involving_post_collect_COD

          post :checkout_succeeded_general # should remove
          post :shipping_first
          post :human_involving_after_order_placed_general

          
          #SHARED
          post :checkout_failed # should remove
          post :shipping

          patch :shipping
          patch :shipping_first
          patch :shipping_COD
          patch :human_involving_after_order_placed_COD
          patch :human_involving_post_collect_COD
          patch :human_involving_after_order_placed_general
          patch :human_involving_after_money_placed
          patch :human_involving_after_money_checked
          patch :human_involving_after_shipped
          patch :human_involved_edit
          

          post :human_involved_edit
          post :human_involving_after_money_placed
          post :human_involving_after_money_checked
          post :human_involving_after_shipped
          post :close_deal
          post :to_abnormal

          get '/info_hub/:event' => 'orders#info_hub'
          post '/info_hub/:event' => 'orders#update_from_info_hub'

          get 'detail' => 'orders#detail'

        end

        collection do
          #金流：查詢交易狀態
          get "query_order_status/:id" => "orders#query_order_status", :as => "query_order"
          get "receive_order_status" => "orders#receive_order_status"

          get '/todolist' , action: 'index'
          get '/shipped' , action: 'shipped'
          get '/pending' , action: 'pending'
          get '/human_involved' , action: 'human_involved'
          #get '/history' , action: 'history'
          match 'history' => 'orders#history', via: [:get, :post], as: :history
          
        end

      end

      resources :orderasks, :only => [:index, :update] do
        collection do 
          get 'history', action: 'history'
        end
      end
      resources :users , :only => [:index, :show] do 
        collection do 
          get 'export', action: 'export'
          #get 'search', action: 'search'
        end
      end
      resources :deliveries

      delete 'peditor/deletePhoto/:id'        => 'peditor#destroyPhoto'
        
    

    #get '/camaadministrator/login' => 'devise/sessions#new'
    #unauthenticated :admin do
      #root to: redirect('/camaadministrator/login'), as: 'unauthenticated_root' # => "devise/sessions#new"
    #end
    
  end

  get '(*url)'   => 'errors#index'

end

app/controllers/statics_controller.rb
#encoding: utf-8
class StaticsController < ApplicationController
  layout false , only: [:index]

  def index
    
    @index_sliders = Banner.includes(:galleries).where(type: 'IndexSlider', status: 'enable').limit(5)
    @jobs = Job.where(status: 'enable')
    @announcements = Announcement.includes(:galleries).for_index.limit(3)
    @announcement_length = 26

    @talk = Talk.first
  
    # 只顯示未下架產品
    active_product_ids = Product.where(status: 'enable')
    @recommended_products = Banner.where(type: 'SelectedProduct', status: 'enable', related_product_id: active_product_ids ).limit(3)
    

  end

  def about

  end

  def show
  
    if params[ :page ].nil?
      redirect_to :index
    end
    
    respond_to do | format |
      format.html { render :template => 'statics/' + params[ :page ]  rescue redirect_to '/errors' }
    end
    
  end

end

app/views/statics/beverages.html.erb
<% title '店內飲品' %>
<link href="/css/drink.css" rel="stylesheet">

<% content_for :header do %>
    <div id="banner">
    <div class="container row">
      <div class="col-md-3 col-md-offset-9 col-sm-12">店內飲品</div>
    </div>
  </div>
<% end %>

<article class="container-fluid">
  <section class="container row">
    <div class="col-md-8 col-md-offset-2 col-sm-12" >
      <div class="content">
        <h3>現烘焙咖啡  Fresh Roast Coffee</h3>
        <div class="clearfix">
          <div class="pull-left text-center"><img src="/images/drk-02.png" class="img-responsive"></div>
          <div class="pull-right">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="78%">&nbsp;</td>
                <td width="11%">熱</td>
                <td width="11%" class="mark">冰</td>
              </tr>
              <tr>
                <td>黑咖啡 Americano </td>
                <td>40</td>
                <td class="mark">40</td>
              </tr>
              <tr>
                <td>濃縮咖啡 Single Espresso </td>
                <td>40</td>
                <td class="mark">-</td>
              </tr>
              <tr>
                <td>特調咖啡 Coffee Flavored </td>
                <td>50</td>
                <td class="mark">50</td>
              </tr>
              <tr>
                <td>卡布奇諾 Cappuccino</td>
                <td>60</td>
                <td class="mark">60</td>
              </tr>
              <tr>
                <td>拿鐵 Latte</td>
                <td>60</td>
                <td class="mark">60</td>
              </tr>
              <tr>
                <td>榛果拿鐵 Hazelnut Latte </td>
                <td>70</td>
                <td class="mark">70</td>
              </tr>
              <tr>
                <td>香草拿鐵 Vanilla Latte </td>
                <td>70</td>
                <td class="mark">70</td>
              </tr>
              <tr>
                <td>焦糖瑪琪朵 Caramel Macchiato </td>
                <td>70</td>
                <td class="mark">70</td>
              </tr>
              <tr>
                <td>杏仁牛奶咖啡 Almond Latte </td>
                <td>70</td>
                <td class="mark">70</td>
              </tr>
              <tr>
                <td>摩卡咖啡 Chocolate Mocha </td>
                <td>70</td>
                <td class="mark">70</td>
              </tr>
            </table>
          </div>
        </div>
      </div>
      <div class="content">
        <h3>濃郁巧克力   Chocolate</h3>
        <div class="clearfix">
          <div class="pull-left text-center"><img src="/images/drk-03.png" class="img-responsive"></div>
          <div class="pull-right">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="78%">&nbsp;</td>
                <td width="11%">熱</td>
                <td width="11%" class="mark">冰</td>
              </tr>
              <tr>
                <td>威士忌巧克力奶昔 Whisky Chocolate </td>
                <td>65</td>
                <td class="mark">65</td>
              </tr>
              <tr>
                <td>薄荷巧克力奶昔 Mint Chocolate </td>
                <td>65</td>
                <td class="mark">65</td>
              </tr>
              <tr>
                <td>橘酒巧克力奶昔 Orange Chocolate</td>
                <td>65</td>
                <td class="mark">65</td>
              </tr>
            </table>
          </div>
        </div>
      </div>
      <div class="content">
        <h3>世界特產茶 Juice &amp; Tea</h3>
        <div class="clearfix">
          <div class="pull-left text-center"><img src="/images/drk-04.png" class="img-responsive"></div>
          <div class="pull-right">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="78%">&nbsp;</td>
                <td width="11%">熱</td>
                <td width="11%" class="mark">冰</td>
              </tr>
              <tr>
                <td>集集紫蘇梅汁 Perilla Plum Juice</td>
                <td>35</td>
                <td class="mark">35</td>
              </tr>
              <tr>
                <td>日式烘烤煎茶 Japanese Roasted Tea</td>
                <td>35</td>
                <td class="mark">35</td>
              </tr>
              <tr>
                <td>德國花草茶 Herbal Tea </td>
                <td>35</td>
                <td class="mark">35</td>
              </tr>
              <tr>
                <td>皇家奶茶 Royal Milk Tea </td>
                <td>35</td>
                <td class="mark">35</td>
              </tr>
            </table>
          </div>
        </div>
      </div>
      <div class="content">
        <h3>天然純釀醋 Vinegar</h3>
        <div class="clearfix">
          <div class="pull-left text-center"><img src="/images/drk-05.png" class="img-responsive"></div>
          <div class="pull-right">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="78%">&nbsp;</td>
                <td width="11%">熱</td>
                <td width="11%" class="mark">冰</td>
              </tr>
              <tr>
                <td>純釀梅子醋 Plum Vinegar </td>
                <td>-</td>
                <td class="mark">40</td>
              </tr>
              <tr>
                <td>蔓越莓醋 Cranberry Vinegar </td>
                <td>-</td>
                <td class="mark">40</td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>
</article>

app/views/statics/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="我們深知一杯美味咖啡的各項環節與要素。 所以選擇在店內精準演繹整個 Bean-to-Cup 流程。手工挑豆、得宜烘焙、即時研磨、專業吧台技術…從一顆生豆到一杯咖啡，最透明的製作流程，提供最真誠的賞味體驗。">
  <meta name="keywords" content="咖啡,coffee,cafe,cama,咖啡豆,精品咖啡,新鮮,烘培,單品,產地,加盟,耳掛,拿鐵,fresh,specialty coffee,green bean,roaster,daily,latte,franchise">
  
  <title>cama 現烘咖啡專門店 -[cama café]</title>
  
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="SHORTCUT ICON" href="/images/favicon.ico">
  <!-- Bootstrap -->
  <link href="/css/reset.css" rel="stylesheet">
  <link href="/css/bootstrap.min.css" rel="stylesheet">
  <link href="/css/jquery.bxslider.css" rel="stylesheet">
  <link href="/css/index.css" rel="stylesheet">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <script>
    window.onload= function() {
    <% if !flash[:notice].nil? %>
     alertify['success']('<%= flash[:notice] %>', 2000);
    <% end %>
    
    <% if !flash[:warning].nil? %>
    alertify['error']("<%= flash[:warning].html_safe %>", 2000); 
    <% end %>
  }
  </script>
  <script>
    jQuery(function($){
      $("a").focus(function(){
      $(this).blur();
    });
  });
  </script>  
</head>
<body>
  <%= render 'layouts/index_header' %>  
  <article class="container-fluid">
    <div class="container">
      <section id="news">
        <header class="row">
          <div class="col-sm-6">
            <h3>最新消息</h3>
          </div>
          <div class="col-sm-3 hidden-xs more text-right">
            <%= link_to announcements_path do %>
              <img src="images/idx-04.png">
            <% end %>
          </div>
        </header>

        <article class="row">
          <% @announcements.each do |announcement| %>
            <div class="col-sm-3"> 
              <%= link_to announcement_path(announcement) do %>
                <div class="hidden-xs cover">
                  <% if announcement.galleries.first %>
                      <% announcement_cover_url = announcement.galleries.first.attachment.url %>
                      <%= image_tag announcement_cover_url , class:"img-responsive" if announcement_cover_url %>
                    <% end %>
                  <div class="date"><b><%= announcement.created_at.strftime("%d")%></b><br>
                      <%= announcement.created_at.strftime("%-m月")%></div>
                </div>
            <div class="title"><% if (announcement.title.length > @announcement_length) %><% note = announcement.title.first(@announcement_length)  %>
                          <%= note+"..." %>
                      <% else %>
                          <%= announcement.title %>
                      <% end %></div>                
              <% end %>
            </div>
          <% end %>
          <div class="col-sm-3 hidden-xs link">
            <%= link_to stores_path do %>
            <% end %>
          </div>
          
        </article>
      </section>
      
      <section id="rcm">
        <h3>cama 經典推薦</h3>
        <article class="row">
          <% @recommended_products.each do | selected_product | %>
            <% rcm_product = Product.find(selected_product.related_product_id) %>
            <div class="col-sm-4 clearfix">
              <div class="pull-left"> 
                <%= link_to( image_tag(rcm_product.galleries.select{ |v| v['type'] == 'ProductPhotoGallery' }.first.attachment.url, class: "img-responsive"), category_product_path(rcm_product.product_cate, rcm_product) ) unless selected_product.related_product_id == 0 || rcm_product.galleries.select{ |v| v['type'] == 'ProductPhotoGallery' }.first.nil? %>
              </div>
              <div class="pull-right">
                <h6><span>●</span><b><%= link_to(rcm_product.name, category_product_path(rcm_product.product_cate, rcm_product) ) %></b><span>●</span></h6>
                <p><%= selected_product.description%>
                </p>
              </div>
              
            </div>
          <% end %>
        </article>
      </section>

      <section id="link" class="visible-xs"><a href="javascript:void(0)"></a></section>

      <section id="talk">
        <div class="row">
          <div class=" col-sm-4 col-sm-offset-7 col-xs-10 col-xs-offset-1">
            <% unless @talk.nil? %>
              <h4><%= @talk.title %></h4>
              <p>
              <% if @talk.subtitle && @talk.subtitle.length > 0 %>
                <%= @talk.subtitle.first(63) %>
                <%= '...' if @talk.subtitle.length > 63 %>
              <% end %>
              </p>
              <%= link_to talk_path(@talk) do %>
                <img src="images/idx-08.png">
              <% end %>
            <% end %>
          </div>

        </div>
      </section>

      <section id="recruit">
      <% if @jobs.count > 0 %>
        <h3>想加入cama嗎？</h3>
        <% @jobs.each do |job| %>
          <%= link_to "#{job.name}", job.websiteurl , target: "_blank" %> 
        <% end %>
      <% end %>
      </section>

    </div>
  </article>
  
  <%= render 'layouts/front_shared_footer' %>
  
  <script src="/js/bootstrap.min.js"></script> 
  <script src="/js/jquery.bxslider.min.js"></script> 
  <script src="js/jquery.parallax-1.1.3.js"></script> 
<script src="js/SmoothScroll.js"></script> 
<script src="js/TweenMax.min.js"></script> 
<script src="js/jquery.superscrollorama.js"></script> 
<script>
  $(document).ready(function(){
    $('.bxslider').bxSlider({
      controls:false,
      auto:true
    });
    $('#talk').parallax({offsetY:500,speedFactor:0.18}); 

  });    
</script>
<script>
jQuery(document).ready(function(){  
  var controller = $.superscrollorama();  
  controller.addTween('#rcm h3', TweenMax.from( 
    $('#rcm article'),  1 ,  {css:{
      opacity:0,
      'position':'relative',
      'top':'50px'
    }}
  ));
});
</script>

</body>

</html>

app/views/statics/returns.html.erb
<% title '退換貨須知' %>
<link href="/css/notice.css" rel="stylesheet">
<% content_for :header do %>
<div id="banner">
  <div class="container row">
    <div class="col-md-4 col-md-offset-8 col-sm-12">退換貨須知</div>
  </div>
</div>
<% end %>
<article class="container-fluid">
  <section class="container row">
    <div class="col-md-8 col-md-offset-2 col-sm-12" >
      <p>一、退換貨限制與規則：<br>
        於本網站完成購物，可於收貨後七天內退換商品，相關說明如下：<br>
        <br>
        退貨：<br>
      <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
          <td valign="top" style="width:20px">•</td>
          <td>咖啡豆、耳掛包等新鮮烘焙商品因具有賞味期限，恕不接受退貨。</td>
        </tr>
        <tr>
          <td valign="top" style="width:20px">•</td>
          <td>請將商品連同發票寄回cama總公司（台北市大安區信義路四段155號12樓 ），並同時寫信至 <a href="mailto:service@camacafe.com" target="_blank">service@camacafe.com </a>描述貨品狀況與運費。退款時，我們將一併退還您的運費。</td>
        </tr>
      </table>
      </p>
      <p> 換貨：<br>
      <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
          <td valign="top" style="width:20px">•</td>
          <td>您所退回的商品必須保持商品本體、內外包裝、配件、贈品、保證書等的完整性，請勿缺漏任何附件或損毀外盒。</td>
        </tr>
        <tr>
          <td valign="top" style="width:20px">•</td>
          <td>請您以送貨時之原包裝紙箱或紙袋，將退貨商品包裝妥當，若原紙箱紙袋已遺失或破損，請另使用其他紙箱包覆於商品原廠包裝之外，請勿直接於原廠包裝上黏貼紙張或書寫文字。</td>
        </tr>
        <tr>
          <td valign="top" style="width:20px">•</td>
          <td>換貨時，我們無法為您將商品A換為商品B。若您欲換成其他品項或規格，請先辦理原商品退貨，再重新訂購您所需要的商品。</td>
        </tr>
      </table>
      </p>
      <p>二、辦理退換貨時，若商品有下列情形者，可能會被認定為已逾越檢查商品之必要程度，而將影響退貨的權利，或需負擔毀壞之費用：<br>
        <br>
      <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
          <td valign="top" style="width:20px">•</td>
          <td>咖啡類耗材（濾紙類等）：除瑕疵商品外，退回之商品已拆封，或包裝不完整（欠損商品、附件、外盒等）。</td>
        </tr>
        <tr>
          <td valign="top" style="width:20px">•</td>
          <td>器具類 ( 杯子、電器品、湯匙、濾杯…等 )：除瑕疵商品外，退回之商品已拆封（運送用包裝外的一切包裝，包括但不限於封膜等接觸商品內容之包裝部分，如封條移除、貼膠移除或標籤撕除等情形），或已非全新狀態（外觀刮傷、破損、受潮…等），與非完整包裝（商品、配件、外盒、保護袋、保麗龍、隨貨文件等有所欠損）。若原廠包裝損毀，將無法退貨，或須將損壞費用於退款中扣抵。</td>
        </tr>
      </table>
      <br>
      若您在訂購商品前或收到商品後，希望更進一步了解商品的使用方式，或對該產品有任何疑慮，歡迎隨時來信 <a href="mailto:service@camacafe.com" target="_blank">service@camacafe.com </a> 或來電 02-2755-0068 與客服人員連絡。
      </p>
    </div>
  </section>
</article>